id: I4BBF4DB0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T22:43:55+00:00'
last_modified: '2022-06-08T09:23:12.882333+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29523
  title: འཇིག་རྟེན་ཀུན་ཏུ་དགའ་བའི་གཏམ་ངག་གི་རོལ་མཚོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D93D:
      image_group_id: I1KG22697
      title: ''
      total_pages: 370
      order: 1
      base_file: D93D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
