id: P009208
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 19:28:06.830031
source_metadata:
  id: bdr:W29523
  title: འཇིག་རྟེན་ཀུན་ཏུ་དགའ་བའི་གཏམ་ངག་གི་རོལ་མཚོ།
  author: ''
  volumes:
    f7dd575142a349cd8760a8ecc16abbb9:
      image_group_id: I1KG22697
      title: ''
      volume_number: 1
      total_pages: 370
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
